services:
  postgres:
    image: postgres:15-alpine
    container_name: api-recetas-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-api_recetas_postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Montar la carpeta local `database` para ejecutar scripts de inicialización
      - ./database:/docker-entrypoint-initdb.d:ro
    networks:
      - api-recetas-network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:8.11
    container_name: api-recetas-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@recetas.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8082:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json:ro
    networks:
      - api-recetas-network
    restart: unless-stopped

  backend:
    build:
      context: ./Springboot
      dockerfile: Dockerfile
    container_name: api-recetas-backend
    depends_on:
      - postgres
    ports:
      - "127.0.0.1:8081:8081"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL:-jdbc:postgresql://postgres:5432/api_recetas_postgres}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      # Orígenes permitidos para CORS: añadir la IP pública del servidor y orígenes de desarrollo
      APP_CORS_ALLOWED_ORIGINS: ${APP_CORS_ALLOWED_ORIGINS:-http://168.181.187.137,http://localhost:5173,http://localhost}
      # Semilla opcional para selección determinística de "receta del día"
      APP_RECETA_DEL_DIA_SEED: ${APP_RECETA_DEL_DIA_SEED:-recetas_demo_seed}
      # JWT
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_MS: ${JWT_EXPIRATION_MS:-3600000}
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8081/actuator/health || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 5
    networks:
      - api-recetas-network
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data:

networks:
  api-recetas-network:
    driver: bridge