-- Script corregido para migrar datos del dump MySQL a PostgreSQL
-- Ejecutar en orden: usuario, categoria, pais, receta

-- Insertar usuarios (evitando duplicados)
INSERT INTO usuario (nombre, apellido, "user", password, activo) VALUES
('Claudio', 'Sanchez', 'claudio', '$2a$10$encrypted_password', 1),
('Juan', 'Perez', 'juan', '$2a$10$encrypted_password', 1),
('Maria', 'Lopez', 'maria', '$2a$10$encrypted_password', 1),
('Pedro', 'Ramirez', 'pedro', '$2a$10$encrypted_password', 1)
ON CONFLICT ("user") DO NOTHING;

-- Insertar categorías (evitando duplicados)
INSERT INTO categoria (nombre, estado, fecha_creacion, imagen, id_usr) VALUES
('Desayuno', 1, CURRENT_TIMESTAMP, 'desayuno.jpg', 1),
('Carne de res', 1, CURRENT_TIMESTAMP, 'carne_res.jpg', 1),
('Pollo', 1, CURRENT_TIMESTAMP, 'pollo.jpg', 1),
('Pescado', 1, CURRENT_TIMESTAMP, 'pescado.jpg', 1),
('Pasta', 1, CURRENT_TIMESTAMP, 'pasta.jpg', 1),
('Ensaladas', 1, CURRENT_TIMESTAMP, 'ensaladas.jpg', 1),
('Sopas', 1, CURRENT_TIMESTAMP, 'sopas.jpg', 1),
('Postres', 1, CURRENT_TIMESTAMP, 'postres.jpg', 1),
('Bebidas', 1, CURRENT_TIMESTAMP, 'bebidas.jpg', 1),
('Vegetariano', 1, CURRENT_TIMESTAMP, 'vegetariano.jpg', 1),
('Vegano', 1, CURRENT_TIMESTAMP, 'vegano.jpg', 1),
('Sin gluten', 1, CURRENT_TIMESTAMP, 'sin_gluten.jpg', 1),
('Bajo en calorías', 1, CURRENT_TIMESTAMP, 'bajo_calorias.jpg', 1),
('Rápido y fácil', 1, CURRENT_TIMESTAMP, 'rapido_facil.jpg', 1),
('Internacional', 1, CURRENT_TIMESTAMP, 'internacional.jpg', 1)
ON CONFLICT (nombre) DO NOTHING;

-- Insertar países (evitando duplicados)
INSERT INTO pais (nombre, url_imagen, estado, fecha_creacion, id_usr) VALUES
('EEUU', 'eeuu.jpg', 1, CURRENT_TIMESTAMP, 1),
('Británico', 'british.jpg', 1, CURRENT_TIMESTAMP, 1),
('Canadiense', 'canada.jpg', 1, CURRENT_TIMESTAMP, 1),
('Mexicano', 'mexico.jpg', 1, CURRENT_TIMESTAMP, 1),
('Italiano', 'italy.jpg', 1, CURRENT_TIMESTAMP, 1),
('Francés', 'france.jpg', 1, CURRENT_TIMESTAMP, 1)
ON CONFLICT (nombre) DO NOTHING;

-- Insertar algunas recetas de ejemplo (con ingredientes y preparación separados por ;)
INSERT INTO receta (nombre, url_imagen, ingrediente, preparacion, estado, id_cat, id_pais, fecha_creacion, id_usr) VALUES
('Panqueques de Banana', 'panqueques_banana.jpg', '2 bananas maduras machacadas;1 taza de harina;1 huevo;1 taza de leche;1 cucharadita de polvo para hornear;2 cucharadas de azúcar;1 pizca de sal;mantequilla para cocinar', 'Mezclar todos los ingredientes secos en un bowl;Agregar el huevo y la leche, mezclar hasta que quede homogéneo;Incorporar las bananas machacadas;Calentar una sartén con mantequilla;Verter la mezcla y cocinar hasta que aparezcan burbujas;Dar vuelta y cocinar el otro lado;Servir calientes', 1, 1, 1, CURRENT_TIMESTAMP, 1),
('Tacos de Carne Asada', 'tacos_carne.jpg', '500g de carne de res para asar;2 limones;1 cebolla;cilantro al gusto;tortillas de maíz;1 cucharadita de comino;1 cucharadita de paprika;sal y pimienta', 'Marinar la carne con limón, comino, paprika, sal y pimienta por 1 hora;Cortar la cebolla en rodajas;Calentar una parrilla o sartén;Asar la carne hasta que esté cocida;Reposar la carne 5 minutos y cortar en tiras;Calentar las tortillas;Armar los tacos con carne, cebolla y cilantro', 1, 2, 4, CURRENT_TIMESTAMP, 2),
('Pollo con Verduras', 'pollo_verduras.jpg', '4 pechugas de pollo;2 zanahorias;1 brócoli;1 pimiento rojo;1 cebolla;2 dientes de ajo;aceite de oliva;sal y pimienta', 'Cortar el pollo en trozos;Cortar todas las verduras en trozos medianos;Calentar aceite en una sartén;Dorar el pollo con ajo y cebolla;Agregar las verduras;Salpimentar;Cocinar hasta que el pollo esté listo y las verduras tiernas', 1, 3, 6, CURRENT_TIMESTAMP, 3),
('Salmón al Horno', 'salmon_horno.jpg', '4 filetes de salmón;2 limones;2 dientes de ajo;1 cucharada de aceite de oliva;1 cucharadita de romero;1 cucharadita de tomillo;sal y pimienta', 'Precalentar el horno a 200°C;Colocar el salmón en una bandeja para horno;Exprimir el limón sobre el salmón;Picar el ajo y esparcir sobre el pescado;Agregar las hierbas, aceite, sal y pimienta;Hornear por 15-20 minutos hasta que esté cocido', 1, 4, 6, CURRENT_TIMESTAMP, 4),
('Pasta Carbonara', 'pasta_carbonara.jpg', '400g de spaghetti;200g de panceta;2 huevos;100g de queso parmesano;1 diente de ajo;pimienta negra;aceite de oliva', 'Cocinar la pasta en agua con sal hasta al dente;Cortar la panceta en trozos pequeños;Dorar la panceta con ajo en una sartén;Batir los huevos con queso parmesano y pimienta;Escurrir la pasta y reservar agua;Mezclar la pasta con la panceta;Agregar la mezcla de huevo fuera del fuego;Agregar agua de cocción si es necesario;Servir inmediatamente', 1, 5, 5, CURRENT_TIMESTAMP, 1);
('Pasta Carbonara', 'Clásica pasta italiana con huevo y panceta', 'pasta_carbonara.jpg', '400g de spaghetti;200g de panceta;2 huevos;100g de queso parmesano;1 diente de ajo;pimienta negra;aceite de oliva', 'Cocinar la pasta en agua con sal hasta al dente;Cortar la panceta en trozos pequeños;Dorar la panceta con ajo en una sartén;Batir los huevos con queso parmesano y pimienta;Escurrir la pasta y reservar agua;Mezclar la pasta con la panceta;Agregar la mezcla de huevo fuera del fuego;Agregar agua de cocción si es necesario;Servir inmediatamente', 20, 'Medio', (SELECT id FROM categoria WHERE nombre = 'Pasta'), (SELECT id FROM pais WHERE nombre = 'Italiano'), (SELECT id FROM usuario WHERE email = 'claudio@gmail.com'), CURRENT_TIMESTAMP),
('Ensalada César', 'Ensalada clásica con aderezo César', 'ensalada_cesar.jpg', '1 lechuga romana;100g de crutones;50g de queso parmesano;2 filetes de anchoa;1 huevo;2 dientes de ajo;1 limón;aceite de oliva;mostaza', 'Lavar y cortar la lechuga;Preparar el aderezo mezclando anchoa, ajo, huevo, limón, mostaza y aceite;Agregar queso parmesano al aderezo;Mezclar la lechuga con el aderezo;Agregar crutones y más queso;Servir fría', 15, 'Fácil', (SELECT id FROM categoria WHERE nombre = 'Ensaladas'), (SELECT id FROM pais WHERE nombre = 'Internacional'), (SELECT id FROM usuario WHERE email = 'juan@gmail.com'), CURRENT_TIMESTAMP),
('Sopa de Tomate', 'Sopa cremosa de tomate casera', 'sopa_tomate.jpg', '1kg de tomates maduros;1 cebolla;2 dientes de ajo;500ml de caldo de verduras;100ml de crema;aceite de oliva;albahaca;sal y pimienta', 'Cortar los tomates por la mitad;Picar cebolla y ajo;Dorar la cebolla y ajo en aceite;Cocinar los tomates hasta que se ablanden;Agregar caldo y hervir 20 minutos;Licuar la sopa;Agregar crema y albahaca;Salpimentar;Servir caliente', 35, 'Fácil', (SELECT id FROM categoria WHERE nombre = 'Sopas'), (SELECT id FROM pais WHERE nombre = 'Internacional'), (SELECT id FROM usuario WHERE email = 'maria@gmail.com'), CURRENT_TIMESTAMP),
('Tiramisú', 'Postre italiano clásico con café y mascarpone', 'tiramisu.jpg', '500g de mascarpone;4 huevos;100g de azúcar;300ml de café fuerte;200g de bizcochos;50g de cacao en polvo;ron o brandy opcional', 'Separar yemas de claras;Batir yemas con azúcar hasta blanquear;Agregar mascarpone a las yemas;Batir claras a punto de nieve;Incorporar claras a la mezcla;Remojar bizcochos en café (con ron opcional);Armar capas alternas de bizcochos y crema;Refrigerar por 4 horas;Espolvorear cacao antes de servir', 30, 'Medio', (SELECT id FROM categoria WHERE nombre = 'Postres'), (SELECT id FROM pais WHERE nombre = 'Italiano'), (SELECT id FROM usuario WHERE email = 'pedro@gmail.com'), CURRENT_TIMESTAMP),
('Limonada Natural', 'Refrescante bebida de limón casera', 'limonada.jpg', '6 limones;100g de azúcar;1 litro de agua;hojas de menta opcional;hielo', 'Exprimir el jugo de los limones;Disolver el azúcar en agua caliente;Mezclar jugo de limón con agua azucarada;Agregar hielo;Decorar con menta si se desea;Servir fría', 10, 'Fácil', (SELECT id FROM categoria WHERE nombre = 'Bebidas'), (SELECT id FROM pais WHERE nombre = 'Internacional'), (SELECT id FROM usuario WHERE email = 'claudio@gmail.com'), CURRENT_TIMESTAMP),
('Hamburguesa Vegetariana', 'Hamburguesa deliciosa sin carne', 'hamburguesa_veg.jpg', '400g de lentejas cocidas;1 cebolla;2 dientes de ajo;1 zanahoria;1 huevo;pan rallado;especias;pan de hamburguesa;lechuga;tomate', 'Picar cebolla, ajo y zanahoria;Mezclar con lentejas cocidas;Agregar huevo, pan rallado y especias;Formar hamburguesas;Freír o hornear hasta dorar;Armar con pan, lechuga y tomate', 25, 'Fácil', (SELECT id FROM categoria WHERE nombre = 'Vegetariano'), (SELECT id FROM pais WHERE nombre = 'Internacional'), (SELECT id FROM usuario WHERE email = 'juan@gmail.com'), CURRENT_TIMESTAMP),
('Galletas de Chocolate', 'Galletas crujientes con chips de chocolate', 'galletas_chocolate.jpg', '200g de harina;100g de mantequilla;100g de azúcar;1 huevo;100g de chips de chocolate;1 cucharadita de vainilla;1/2 cucharadita de bicarbonato;1 pizca de sal', 'Precalentar horno a 180°C;Blandir mantequilla con azúcar;Agregar huevo y vainilla;Mezclar harina, bicarbonato y sal;Incorporar chips de chocolate;Formar bolitas y aplastar ligeramente;Hornear 10-12 minutos;Enfriar antes de comer', 20, 'Fácil', (SELECT id FROM categoria WHERE nombre = 'Postres'), (SELECT id FROM pais WHERE nombre = 'EEUU'), (SELECT id FROM usuario WHERE email = 'maria@gmail.com'), CURRENT_TIMESTAMP),
('Pizza Margarita', 'Pizza clásica italiana con tomate, mozzarella y albahaca', 'pizza_margarita.jpg', '500g de masa para pizza;200g de salsa de tomate;250g de mozzarella;hojas de albahaca fresca;aceite de oliva;sal', 'Precalentar horno a 250°C;Estirar la masa en forma redonda;Untar salsa de tomate;Agregar mozzarella en rodajas;Decorar con albahaca y aceite;Hornear por 10-15 minutos hasta dorar', 25, 'Medio', (SELECT id FROM categoria WHERE nombre = 'Internacional'), (SELECT id FROM pais WHERE nombre = 'Italiano'), (SELECT id FROM usuario WHERE email = 'pedro@gmail.com'), CURRENT_TIMESTAMP),
('Arroz con Pollo', 'Plato tradicional con pollo y arroz', 'arroz_pollo.jpg', '500g de pollo en trozos;200g de arroz;1 cebolla;2 dientes de ajo;1 pimiento;500ml de caldo;azafrán o colorante;azafrán o colorante;aceite de oliva;sal y pimienta', 'Dorar el pollo en aceite;Agregar cebolla, ajo y pimiento picados;Cocinar el arroz con el pollo;Cocinar el arroz con el pollo;Agregar caldo y azafrán;Cocinar a fuego lento hasta que el arroz esté listo;Reposar 5 minutos antes de servir', 40, 'Medio', (SELECT id FROM categoria WHERE nombre = 'Pollo'), (SELECT id FROM pais WHERE nombre = 'Internacional'), (SELECT id FROM usuario WHERE email = 'claudio@gmail.com'), CURRENT_TIMESTAMP),
('Sushi Rolls', 'Rollos de sushi caseros', 'sushi_rolls.jpg', '200g de arroz para sushi;4 hojas de nori;100g de salmón fresco;100g de pepino;100g de aguacate;vinagre de arroz;azúcar;sal;wasabi opcional', 'Cocinar el arroz y condimentar con vinagre, azúcar y sal;Cortar salmón, pepino y aguacate en tiras;Colocar nori sobre esterilla;Extender arroz sobre nori;Agregar relleno en el centro;Enrollar apretando bien;Cortar en rodajas;Servir con wasabi', 30, 'Difícil', (SELECT id FROM categoria WHERE nombre = 'Internacional'), (SELECT id FROM pais WHERE nombre = 'Internacional'), (SELECT id FROM usuario WHERE email = 'juan@gmail.com'), CURRENT_TIMESTAMP),
('Lasaña de Carne', 'Lasaña clásica con carne molida y queso', 'lasana_carne.jpg', '500g de carne molida;12 placas de lasaña;500ml de salsa de tomate;300g de queso ricotta;200g de mozzarella;1 cebolla;2 dientes de ajo;aceite de oliva;especias', 'Dorar cebolla y ajo en aceite;Agregar carne molida y cocinar;Cocinar placas de lasaña según instrucciones;Mezclar ricotta con especias;Armar capas: salsa, placas, ricotta, mozzarella;Repetir capas;Hornear a 180°C por 30 minutos', 45, 'Medio', (SELECT id FROM categoria WHERE nombre = 'Pasta'), (SELECT id FROM pais WHERE nombre = 'Italiano'), (SELECT id FROM usuario WHERE email = 'maria@gmail.com'), CURRENT_TIMESTAMP),
('Ceviche de Camarón', 'Ceviche fresco de camarón', 'ceviche_camaron.jpg', '500g de camarones frescos;4 limones;1 cebolla roja;1 ají;cilantro;sal;aceite de oliva', 'Pelar y limpiar camarones;Cortar en trozos pequeños;Cortar cebolla y ají en juliana;Mezclar todo con jugo de limón y sal;Dejar marinar en refrigerador 30 minutos;Agregar cilantro y aceite;Servir frío', 35, 'Fácil', (SELECT id FROM categoria WHERE nombre = 'Pescado'), (SELECT id FROM pais WHERE nombre = 'Internacional'), (SELECT id FROM usuario WHERE email = 'pedro@gmail.com'), CURRENT_TIMESTAMP),
('Brownies de Chocolate', 'Brownies húmedos y deliciosos', 'brownies.jpg', '200g de chocolate negro;150g de mantequilla;150g de azúcar;3 huevos;100g de harina;50g de nueces opcional;1 cucharadita de vainilla;1/2 cucharadita de sal', 'Derretir chocolate con mantequilla;Blandir azúcar con huevos;Agregar chocolate derretido;Mezclar harina, sal y vainilla;Incorporar nueces si se desea;Verter en molde;Hornear a 180°C por 25 minutos', 35, 'Fácil', (SELECT id FROM categoria WHERE nombre = 'Postres'), (SELECT id FROM pais WHERE nombre = 'EEUU'), (SELECT id FROM usuario WHERE email = 'claudio@gmail.com'), CURRENT_TIMESTAMP),
('Quiche Lorraine', 'Quiche clásica con panceta y queso', 'quiche_lorraine.jpg', '1 masa para tarta;200g de panceta;200g de queso gruyere;4 huevos;300ml de crema;1 cebolla;nuez moscada;sal y pimienta', 'Precalentar horno a 180°C;Cocinar panceta hasta dorar;Forrar molde con masa;Distribuir panceta y queso;Batir huevos con crema y especias;Verter sobre el relleno;Hornear por 35-40 minutos', 50, 'Medio', (SELECT id FROM categoria WHERE nombre = 'Internacional'), (SELECT id FROM pais WHERE nombre = 'Francés'), (SELECT id FROM usuario WHERE email = 'juan@gmail.com'), CURRENT_TIMESTAMP),
('Risotto de Champiñones', 'Risotto cremoso con champiñones', 'risotto_champ.jpg', '300g de arroz arborio;300g de champiñones;1 cebolla;2 dientes de ajo;1 litro de caldo de verduras;100ml de vino blanco;50g de queso parmesano;mantequilla;aceite de oliva', 'Calentar caldo y mantener caliente;Cortar champiñones y dorar;Dorar cebolla y ajo en mantequilla;Agregar arroz y tostar;Incorporar vino y reducir;Agregar caldo poco a poco revolviendo;Agregar champiñones y queso;Servir inmediatamente', 30, 'Medio', (SELECT id FROM categoria WHERE nombre = 'Internacional'), (SELECT id FROM pais WHERE nombre = 'Italiano'), (SELECT id FROM usuario WHERE email = 'maria@gmail.com'), CURRENT_TIMESTAMP),
('Chili con Carne', 'Chili picante con carne molida', 'chili_carne.jpg', '500g de carne molida;2 latas de frijoles rojos;1 cebolla;2 dientes de ajo;400g de salsa de tomate;1 pimiento;chile en polvo;comino;aceite de oliva', 'Dorar cebolla, ajo y pimiento;Agregar carne molida y cocinar;Cocinar frijoles y agregar;Incorporar salsa de tomate y especias;Cocinar a fuego lento 30 minutos;Servir caliente', 40, 'Medio', (SELECT id FROM categoria WHERE nombre = 'Carne de res'), (SELECT id FROM pais WHERE nombre = 'Mexicano'), (SELECT id FROM usuario WHERE email = 'pedro@gmail.com'), CURRENT_TIMESTAMP),
('Mousse de Chocolate', 'Mousse ligero de chocolate', 'mousse_chocolate.jpg', '200g de chocolate negro;4 huevos;50g de azúcar;200ml de crema para batir;vainilla', 'Derretir chocolate al baño maría;Separar yemas de claras;Batir yemas con azúcar;Incorporar chocolate derretido;Batir claras a punto de nieve;Batir crema;Mezclar todo suavemente;Refrigerar por 2 horas', 20, 'Medio', (SELECT id FROM categoria WHERE nombre = 'Postres'), (SELECT id FROM pais WHERE nombre = 'Francés'), (SELECT id FROM usuario WHERE email = 'claudio@gmail.com'), CURRENT_TIMESTAMP),
('Falafel', 'Croquetas de garbanzo fritas', 'falafel.jpg', '400g de garbanzos remojados;1 cebolla;2 dientes de ajo;cilantro;comino;cilantro;harina;aceite para freír;sal', 'Procesar garbanzos con cebolla, ajo y cilantro;Agregar especias y harina;Formar bolitas;Freír en aceite caliente hasta dorar;Escurrir en papel absorbente;Servir con tahini o yogurt', 25, 'Medio', (SELECT id FROM categoria WHERE nombre = 'Vegano'), (SELECT id FROM pais WHERE nombre = 'Internacional'), (SELECT id FROM usuario WHERE email = 'juan@gmail.com'), CURRENT_TIMESTAMP),
('Paella de Mariscos', 'Paella española con mariscos', 'paella_mariscos.jpg', '300g de arroz;300g de mariscos mixtos;1 cebolla;2 dientes de ajo;1 pimiento rojo;azafrán;caldo de pescado;aceite de oliva;guisantes', 'Calentar aceite en paellera;Dorar cebolla, ajo y pimiento;Agregar arroz y azafrán;Incorporar mariscos y guisantes;Agregar caldo caliente;Cocinar sin remover hasta que se absorba;Reposar 5 minutos', 35, 'Medio', (SELECT id FROM categoria WHERE nombre = 'Pescado'), (SELECT id FROM pais WHERE nombre = 'Internacional'), (SELECT id FROM usuario WHERE email = 'maria@gmail.com'), CURRENT_TIMESTAMP),
('Tarta de Manzana', 'Tarta clásica de manzana', 'tarta_manzana.jpg', '1kg de manzanas;2 masas para tarta;100g de azúcar;1 cucharadita de canela;50g de mantequilla;1 huevo para pintar', 'Pelar y cortar manzanas;Mezclar con azúcar y canela;Forrar molde con masa;Agregar relleno de manzana;Cubrir con la otra masa;Pintar con huevo batido;Hornear a 180°C por 40 minutos', 50, 'Medio', (SELECT id FROM categoria WHERE nombre = 'Postres'), (SELECT id FROM pais WHERE nombre = 'Internacional'), (SELECT id FROM usuario WHERE email = 'pedro@gmail.com'), CURRENT_TIMESTAMP),
('Curry de Pollo', 'Curry cremoso de pollo', 'curry_pollo.jpg', '500g de pollo en trozos;1 cebolla;2 dientes de ajo;1 lata de leche de coco;curry en polvo;jengibre;aceite de oliva;cilantro', 'Dorar pollo en aceite;Agregar cebolla, ajo y jengibre;Incorporar curry y leche de coco;Cocinar a fuego lento 20 minutos;Agregar cilantro;Servir con arroz', 30, 'Medio', (SELECT id FROM categoria WHERE nombre = 'Pollo'), (SELECT id FROM pais WHERE nombre = 'Internacional'), (SELECT id FROM usuario WHERE email = 'claudio@gmail.com'), CURRENT_TIMESTAMP),
('Enchiladas Verdes', 'Enchiladas con salsa verde', 'enchiladas_verdes.jpg', '12 tortillas de maíz;500g de pollo cocido;300g de salsa verde;200g de queso;1 cebolla;crema agria;aceite', 'Rellenar tortillas con pollo y queso;Enrollar y colocar en bandeja;Cubrir con salsa verde y queso;Hornear a 180°C por 15 minutos;Decorar con cebolla y crema', 25, 'Fácil', (SELECT id FROM categoria WHERE nombre = 'Pollo'), (SELECT id FROM pais WHERE nombre = 'Mexicano'), (SELECT id FROM usuario WHERE email = 'juan@gmail.com'), CURRENT_TIMESTAMP),
('Ratatouille', 'Estofado provenzal de verduras', 'ratatouille.jpg', '2 berenjenas;2 calabacines;2 pimientos;4 tomates;1 cebolla;2 dientes de ajo;aceite de oliva;hierbas provenzales', 'Cortar todas las verduras en cubos;Dorar cebolla y ajo en aceite;Agregar berenjenas y calabacines;Cocinar pimientos y tomates;Mezclar todo con hierbas;Cocinar a fuego lento 30 minutos', 40, 'Fácil', (SELECT id FROM categoria WHERE nombre = 'Vegetariano'), (SELECT id FROM pais WHERE nombre = 'Francés'), (SELECT id FROM usuario WHERE email = 'maria@gmail.com'), CURRENT_TIMESTAMP),
('Panna Cotta', 'Postre italiano cremoso', 'panna_cotta.jpg', '500ml de crema para batir;100g de azúcar;1 vaina de vainilla;4 hojas de gelatina;frutas para decorar', 'Remojar gelatina en agua fría;Calentar crema con azúcar y vainilla;Disolver gelatina en la crema caliente;Verter en moldes;Refrigerar por 4 horas;Desmoldar y decorar', 15, 'Fácil', (SELECT id FROM categoria WHERE nombre = 'Postres'), (SELECT id FROM pais WHERE nombre = 'Italiano'), (SELECT id FROM usuario WHERE email = 'pedro@gmail.com'), CURRENT_TIMESTAMP),
('Bibimbap', 'Plato coreano con arroz y verduras', 'bibimbap.jpg', '200g de arroz;zanahorias;espinacas;champiñones;1 huevo;salsa gochujang;aceite de sésamo;tofu opcional', 'Cocinar arroz;Cocinar verduras por separado;Freír huevo;Servir arroz con verduras encima;Agregar salsa gochujang;Mezclar todo antes de comer', 25, 'Medio', (SELECT id FROM categoria WHERE nombre = 'Internacional'), (SELECT id FROM pais WHERE nombre = 'Internacional'), (SELECT id FROM usuario WHERE email = 'claudio@gmail.com'), CURRENT_TIMESTAMP),
('Canelones de Espinaca', 'Canelones rellenos de espinaca', 'canelones_espinaca.jpg', '12 placas de canelones;500g de espinacas;300g de ricotta;100g de queso parmesano;1 cebolla;2 dientes de ajo;salsa bechamel', 'Cocinar espinacas y escurrir;Dorar cebolla y ajo;Mezclar con ricotta y queso;Cocinar placas de canelones;Rellenar con mezcla;Cubrir con bechamel y queso;Hornear a 180°C por 20 minutos', 35, 'Medio', (SELECT id FROM categoria WHERE nombre = 'Vegetariano'), (SELECT id FROM pais WHERE nombre = 'Italiano'), (SELECT id FROM usuario WHERE email = 'juan@gmail.com'), CURRENT_TIMESTAMP),
('Pozole', 'Sopa tradicional mexicana', 'pozole.jpg', '500g de maíz pozolero;500g de cerdo;1 cebolla;2 dientes de ajo;chile ancho;orégano;limón;repollo', 'Cocinar maíz hasta reventar;Cocinar cerdo con cebolla y ajo;Agregar maíz cocido;Preparar salsa de chile;Servir con repollo, limón y orégano', 120, 'Difícil', (SELECT id FROM categoria WHERE nombre = 'Carne de res'), (SELECT id FROM pais WHERE nombre = 'Mexicano'), (SELECT id FROM usuario WHERE email = 'maria@gmail.com'), CURRENT_TIMESTAMP),
('Crème Brûlée', 'Postre francés con caramelo', 'creme_brulee.jpg', '500ml de crema;100g de azúcar;4 yemas de huevo;1 vaina de vainilla;azúcar para quemar', 'Calentar crema con vainilla;Blandir yemas con azúcar;Incorporar crema caliente;Verter en ramequines;Hornear al baño maría 40 minutos;Refrigerar;Espolvorear azúcar y quemar con soplete', 50, 'Difícil', (SELECT id FROM categoria WHERE nombre = 'Postres'), (SELECT id FROM pais WHERE nombre = 'Francés'), (SELECT id FROM usuario WHERE email = 'pedro@gmail.com'), CURRENT_TIMESTAMP);
