name: CI

on:
  push:
    branches: [ backend, main ]
  pull_request:
    branches: [ backend, main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven local repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Build and run tests
        run: mvn -B -V test --settings .github/maven-settings.xml || mvn -B -V test

      - name: Upload surefire test reports
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: '**/target/surefire-reports'

  dependency-scan:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: OWASP Dependency-Check scan
        uses: owasp/dependency-check-action@v8
        with:
          project: 'api-recetas'
          scan: './'
          format: 'ALL'

      - name: Upload dependency-check report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: dependency-check-report.*

      - name: Dependency review (GitHub)
        uses: github/dependency-review-action@v2
